/* config.h. Generated by cmake from config.h.cmake */

/* Defined if your compiler supports some byte swap functions */
/* #undef HAVE_BOOST_BYTESWAP */
#define   HAVE_GCC_BYTESWAP 1
/* #undef HAVE_GLIBC_BYTESWAP */
/* #undef HAVE_MSC_BYTESWAP */
/* #undef HAVE_MAC_BYTESWAP */
/* #undef HAVE_OPENBSD_BYTESWAP */

/* Defined if your compiler supports some atomic operations */
/* #undef HAVE_STD_ATOMIC */
/* #undef HAVE_BOOST_ATOMIC */
#define   HAVE_GCC_ATOMIC 1
/* #undef HAVE_MAC_ATOMIC */
/* #undef HAVE_WIN_ATOMIC */
/* #undef HAVE_IA64_ATOMIC */

/* Defined if your compiler supports some safer version of vsprintf */
#define   HAVE_VSNPRINTF 1
/* #undef HAVE_VSPRINTF_S */

/* Defined if your compiler supports ISO _strdup */
/* #undef HAVE_ISO_STRDUP */

/* Defined if zlib is installed */
/* #undef HAVE_ZLIB */
/* #undef HAVE_BOOST_ZLIB */

/* Indicates whether debug messages are shown even in release mode */
/* #undef TRACE_IN_RELEASE */

#define TESTS_DIR "/home/eduardo/Documents/CuarzoPlayer/lib/taglib-1.11.1/tests/"
